version: '3'
services:

  fluree-n1:
    image: fluree/ledger
    container_name: fluree1
    networks:
        - default
    environment: 
        fdb_group_servers: server2@host.docker.internal:9790,server1@192.168.1.12:9790
        fdb_group_this_server: server2
    ports:
     - "8090:8090" 
     - "9790:9790"
