version: '3'
services:
  ledger1:
    image: fluree/ledger
    ports:
      - 8090:8090
      - 9791:9791
    environment: 
      fdb_group_servers: server1@ledger1:9791,server2@ledger2:9792,server3@ledger3:9793
      fdb_group_this_server: server1
  ledger2:
    image: fluree/ledger
    ports:
      - 8091:8090
      - 9792:9792
    environment: 
      fdb_group_servers: server1@ledger1:9791,server2@ledger2:9792,server3@ledger3:9793
      fdb_group_this_server: server2
  ledger3:
    image: fluree/ledger
    ports:
      - 8092:8090
      - 9793:9793
    environment: 
      fdb_group_servers: server1@ledger1:9791,server2@ledger2:9792,server3@ledger3:9793
      fdb_group_this_server: server3
